name: 🚀 Deploy NerdySite on push

on:
  push:
    branches:
      - master  # Trigger the workflow on push or pull request to the 'master' branch

jobs:
  web-deploy:
    name: 🎉 Deploying  NerdySite
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Checking out latest code
      uses: actions/checkout@v4

    - name: 📂 Deploy to FTP
      run: |
        curl --ftp-create-dirs -T "*" -u ${{ secrets.FTP_USER }}:${{ secrets.FTP_PASS }} ftp://${{ secrets.FTP_SERVER }}/home/aisayamc/nerdevolution.tech/
      env:
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASS: ${{ secrets.FTP_PASS}}
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
